# cf. https://sw.kovidgoyal.net/kitty/conf

; ==========================================================================
; Keyboard shortcuts
; ==========================================================================
; ※ The expected behavior depends on other keybindings including Karabiner.

# As `opt+left`
map alt+left send_text all \x1bb
# As `opt+right`
map alt+right send_text all \x1bf
# As `opt+left`
map ctrl+shift+b send_text all \x1bb
# As `opt+right`
map ctrl+shift+f send_text all \x1bf
# As `opt+delete`
map ctrl+shift+d send_text all \x1bd
# As `opt+delete`
map ctrl+shift+w send_text all \x1bd
# As `esc+z`
map cmd+z send_text all \ez
# As `esc+y`
map cmd+shift+z send_text all \ey
