# This is a "Brewfile" that its packages are sorted arbitrarily
# to clarify the installed packages.
# A normal file that lists the installed packages can be created
# by `brew bundle dump` (overwrited with `-f`).
# Run `brew bundle --file macos/x86_64/Brewfile` to install the listed packages
# and uninstall packages not being listed.
# To update packages, it seems `brew upgrade` may be needed and then run `brew bundle`.

#------------------------------------------------
# Taps
#------------------------------------------------
# cf. https://docs.brew.sh/Taps

tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-fonts"
tap "hashicorp/tap"

#------------------------------------------------
# Formulae
#------------------------------------------------
brew ""

#------------------------------------------------
# Casks
#------------------------------------------------

cask "name"

#------------------------------------------------
# VSCode
#------------------------------------------------

vscode "name"
